import Head from 'next/head'
import Heading from 'src/pages/home/components/Heading'
import OurValues from 'src/pages/home/components/OurValues'
import Techs from 'src/pages/home/components/Techs'
import Content from 'src/pages/service/components/Content'


export default function Home() {
  return (
    <div>
      <Head>
        <title>F.Arriagada - Portafolio Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <OurValues />
      <Techs />
      {/* <HowWorks /> */}
      {/* <Services title="Experiencia" services={cardServices}/> */}

      {/* <Content /> */}
      {/* <HowWorks /> */}
    </div>
  )
}
